try {
    throw new Error('Algo salio mal');
} catch  {
    console.log('Hubo un error grave');

}